backend:
  name: Git Gateway #github
  repo: Nikoti9510/blog
  branch: main # Branch to update (optional; defaults to master)

media_folder: "public/assets/img/uploads" # Media files will be stored in the repo under assets/img/uploads
public_folder: "/assets/img/uploads" 

collections:
  - name: "article"
    label: "Article"
    folder: "/src/posts"
    create: true
    slug: "{{slug}}"
    fields: 
      - { label: "Titre", name: "title", widget: "string" }
      - { label: "Descritpion", name: "description", widget: "string" }
      - { label: "Categories", name: "tags", widget: "list", default: ["post"] }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Slug", name: "slug", widget: "string" }
      - { label: "Image de présentation", name: "image", widget: "image" }
      - { label: "Texte de description de l'image", name: "imageAlt", widget: "string" }
      - { label: "Contenu de l'article", name: "body", widget: "markdown" } #body en nom de fichier pour qu'il soit rendu comment le contenu de l'article